export const DbGridNames = {
    DbChangeTrackers : "Database Change Tracker",
    DbChangeTrackers_Cn : "数据更改记录",
    StaffHolidays : "Staff Holiday",
    StaffHolidays_Cn : "员工假期",
    WorkingHours : "Working Hour",
    WorkingHours_Cn : "工作时间",
    StaffAddresses : "Staff Addresses",
    StaffAddresses_Cn : "员工地址",
    Departments : "Departments",
    Departments_Cn : "部门",
    ProfitStatements : "Profit Statements",
    ProfitStatements_Cn : "核账",
    WorkSuggestion : "Work Suggestion",
    WorkSuggestion_Cn : "工作建议",
    WorkRequestMap : "Work Request Map",
    WorkRequestMap_Cn : "工作记录映射",
    Addresses : "Addresses",
    Addresses_Cn : "所有地址",
    PaymentFromCustomers : "Payment From Customers",
    PaymentFromCustomers_Cn : "客户预付款",
    PaymentToSuppliers : "Payment To Suppliers",
    PaymentToSuppliers_Cn : "�付供应商",
    AddressAuthorization : "Address Authorization",
    AddressAuthorization_Cn : "授权地址",
    SenderAddresses : "Sender Addresses",
    SenderAddresses_Cn : "发送地址",
    ReceiverAddresses : "Receiver Addresses",
    ReceiverAddresses_Cn : "接收地址",
    ShipmentOrders : "Shipment Orders",
    ShipmentOrders_Cn : "订单",
    SupplierInvoices : "Supplier Invoices",
    SupplierInvoices_Cn : "供应商发票",
    CustomerInvoices : "Customer Invoices",
    CustomerInvoices_Cn : "客户发票",
    ServiceRequests : "Service Requests",
    ServiceRequests_Cn : "服务请求",
    Emails : "Emails",
    Emails_Cn : "邮件",
    DHLEmailNotifications : "DHLEmailNotifications",
    DHLEmailNotifications_Cn : "DHL通知邮件",
    InvoicedShipments : "Invoiced Shipments",
    InvoicedShipments_Cn : "已出发票运单",
    InvoicedDutyVats : "Invoiced DutyVats",
    InvoicedDutyVats_Cn : "已出关税发票",
    Companies : "Companies",
    Companies_Cn : "公司信息",
    Projects : "Projects",
    Projects_Cn : "项目",
    ServiceChannels : "Service Channels",
    ServiceChannels_Cn : "利润率",
    UnAuthorizedShipments : "UnAuthorized Shipments",
    UnAuthorizedShipments_Cn : "未授权运单",
    Banks : "Banks",
    Banks_Cn : "银行账号",
    Barclays : "Barclays",
    Barclays_Cn : "巴克利银行",
    Santander : "Santander",
    Santander_Cn : "桑坦德銀行",
    AmericanExpress : "American Express",
    AmericanExpress_Cn : "美国运通信用卡",
    AmericanExpressSmall : "American Express Small",
    AmericanExpressSmall_Cn : "美国运通小卡",
    Virgin : "Virgin",
    Virgin_Cn : "维珍信用卡",
    CapitalOnTap : "CapitalOnTap",
    CapitalOnTap_Cn : "CapitalOnTap信用卡",
    CapitalOne : "CapitalOne",
    CapitalOne_Cn : "CapitalOne信用卡",
    ShanghaiPufaBank : "Shanghai Pufa Bank",
    ShanghaiPufaBank_Cn : "浦发银行",
    ChinaConstructionBank : "China Construction Bank",
    ChinaConstructionBank_Cn : "建设银行",
    SantanderCredit : "Santander Credit",
    SantanderCredit_Cn : "Santander信用卡",
    NatwestCredit : "Natwest Credit",
    NatwestCredit_Cn : "Natwest信用卡",
    Costs : "Costs",
    Costs_Cn : "花费",
    Incomes : "Incomes",
    Incomes_Cn : "收入",
    Profit : "Profit",
    Profit_Cn : "利润",
    UKDivident : "UK Divident",
    UKDivident_Cn : "英国分部分红",
    CNDivident : "CN Divident",
    CNDivident_Cn : "中国分部分红",
    CustomerPayments : "Customer Payments",
    CustomerPayments_Cn : "客户付款",
    WorkRequest : "Work Request",
    WorkRequest_Cn : "工作记录",
    UserChangeAudit : "User Change History",
    UserChangeAudit_Cn : "更改历史",
    FileAttachments : "File Attachments",
    FileAttachments_Cn : "附件文件",
    FileAttachmentContent : "File Attachment Content",
    FileAttachmentContent_Cn : "附件目录结构",
    SupplierCompany : "Supplier  Company",
    SupplierCompany_Cn : "供应商",
    PackageList : "Package List",
    PackageList_Cn : "装箱单",
    CustomDeclaration : "Custom Declaration",
    CustomDeclaration_Cn : "海关申报",
    BBS : "BBS",
    BBS_Cn : "论坛",
    Feedbacks : "Feedbacks",
    Feedbacks_Cn : "反馈",
    TrackingHistory : "Tracking History",
    TrackingHistory_Cn : "跟踪信息",
    HostSurcharge : "Host Surcharge",
    HostSurcharge_Cn : "账号费",
    TenantSurcharge : "Tenant Surcharge",
    TenantSurcharge_Cn : "租户费",
    Users : "Users",
    Users_Cn : "用户",
    Tenants : "Tenants",
    Tenants_Cn : "租户",
    Roles : "Roles",
    Roles_Cn : "角色",
    Permissions : "Permissions",
    Permissions_Cn : "访问授权",
    AppSettings : "App Settings",
    AppSettings_Cn : "系统设置",
    HostSurchargeSettings : "Host Surcharge Settings",
    HostSurchargeSettings_Cn : "主机额外收费设置",
    TenantSurchargeSettings : "Tenant Surcharge Settings",
    TenantSurchargeSettings_Cn : "租户额外收费设置",
    FileAttachmentMaps : "File Attachment Maps",
    FileAttachmentMaps_Cn : "附件关联",
    ChildrenSurchargeSettings : "Surcharge Settings",
    ChildrenSurchargeSettings_Cn : "额外收费设置"
}